/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь, профиль председателя, режим запуска */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Сохранить профиль председателя, дом и договор */
        put: operations["saveProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Акты дома председателя (новые сверху) */
        get: operations["listActs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать демо-акт с синтетическими строками (только DEMO_MODE) */
        post: operations["createDemoAct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Карточка акта */
        get: operations["getAct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить шапку акта (поля формы 761/пр) и сведения о получении */
        patch: operations["patchAct"];
        trace?: never;
    };
    "/acts/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить строку акта */
        post: operations["addLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить строку */
        delete: operations["deleteLine"];
        options?: never;
        head?: never;
        /** Изменить строку, её статус, комментарий, оспариваемую сумму */
        patch: operations["patchLine"];
        trace?: never;
    };
    "/lines/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Прикрепить фото или PDF как доказательство (до 10 МБ) */
        post: operations["addEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить доказательство */
        delete: operations["deleteEvidence"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Получить или создать приглашение для жильцов (текстовый диплинк) */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        /** Акт глазами жильца (без цен) */
        get: operations["getInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        get?: never;
        /** Ответы жильца по строкам своего подъезда */
        put: operations["putVotes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сформировать PDF — сопроводительное письмо (sign) или мотивированный отказ (refuse); бот пришлёт файл в чат */
        post: operations["decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отметить отправку документа исполнителю */
        post: operations["dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}/successor": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Новый акт после отправленного отказа (строки копируются, оспоренные помечаются) */
        post: operations["successor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{id}/demo-shift": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Демо-режим — перемотать время демо-акта вперёд */
        post: operations["demoShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подсказки из минимального перечня работ (ПП РФ № 290) */
        get: operations["searchWorks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Действующие правила и их источники */
        get: operations["listRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Файл по подписанной ссылке (ссылки приходят в карточке акта) */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example ACT_LOCKED */
                code: string;
                message: string;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        /** @example 9600.00 */
        Money: string;
        /** Format: date */
        Date: string | null;
        /** @enum {string} */
        Kind: "norm" | "calculation" | "recommendation" | "assumption";
        /** @enum {string} */
        Severity: "ok" | "info" | "warning" | "violation";
        /** @enum {string} */
        Channel: "post" | "email" | "executor_portal" | "in_person" | "other";
        /** @enum {string} */
        Status: "draft" | "in_review" | "decided" | "closed_signed" | "refused_sent" | "deemed_accepted" | "replaced";
        /** @enum {string} */
        ReviewStatus: "unchecked" | "confirmed" | "doubtful" | "not_done";
        Source: {
            id: string;
            title: string;
            short: string;
            cite: string;
            edition: string;
            effective_from?: string;
            effective_to?: string;
            url: string;
            checked_at: string;
            verified: boolean;
        };
        Basis: {
            rule_id: string;
            kind: components["schemas"]["Kind"];
            summary: string;
            source: components["schemas"]["Source"] | null;
            point: string | null;
        };
        Claim: {
            code: string;
            kind: components["schemas"]["Kind"];
            severity: components["schemas"]["Severity"];
            text: string;
            basis: components["schemas"]["Basis"][];
        };
        User: {
            /** Format: uuid */
            id: string;
            max_user_id: number;
            first_name: string;
            last_name: string;
            /** Format: date-time */
            consent_at: string | null;
        };
        Profile: {
            house_id: string | null;
            full_name: string;
            apartment_no: string;
            /** @enum {string} */
            authority_type: "" | "oss_decision" | "power_of_attorney";
            authority_date: components["schemas"]["Date"];
            authority_number: string;
            applicability_confirmed: boolean | null;
        };
        House: {
            /** Format: uuid */
            id: string;
            city: string;
            address: string;
            entrances_count: number;
            timezone: string;
            council_chat_id: number | null;
            is_demo: boolean;
        };
        Contract: {
            id: string;
            /** @enum {string} */
            type: "management" | "services" | "repair";
            number: string;
            date: components["schemas"]["Date"];
            end_date: components["schemas"]["Date"];
            executor_name: string;
        };
        ProfileBundle: {
            user: components["schemas"]["User"];
            profile: components["schemas"]["Profile"] | null;
            house: components["schemas"]["House"] | null;
            contract: components["schemas"]["Contract"] | null;
        };
        Me: components["schemas"]["ProfileBundle"] & {
            /** @enum {string} */
            mode: "chairman" | "resident";
            invite_token?: string;
            demo_mode: boolean;
            bot_username: string;
            profile_complete: boolean;
        };
        ProfileInput: {
            full_name: string;
            apartment_no?: string;
            /** @enum {string} */
            authority_type: "oss_decision" | "power_of_attorney";
            authority_date?: components["schemas"]["Date"];
            authority_number?: string;
            applicability_confirmed?: boolean | null;
            city?: string;
            address: string;
            entrances_count: number;
            executor_name?: string;
            /** @enum {string} */
            contract_type?: "" | "management" | "services" | "repair";
            contract_number?: string;
            contract_date?: components["schemas"]["Date"];
            contract_end_date?: components["schemas"]["Date"];
        };
        /** @description Карточка акта; поля шапки повторяют форму приказа Минстроя № 761/пр */
        Act: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            house_id: string;
            parent_act_id: string | null;
            source_file_id: string | null;
            number: string;
            act_date: components["schemas"]["Date"];
            city: string;
            address: string;
            customer_full_name: string;
            customer_apartment: string;
            customer_authority_text: string;
            executor_name: string;
            executor_signatory_name: string;
            executor_signatory_position: string;
            executor_basis: string;
            /** @enum {string} */
            contract_type: "management" | "services" | "repair";
            contract_number: string;
            contract_date: components["schemas"]["Date"];
            contract_end_date: components["schemas"]["Date"];
            period_from: components["schemas"]["Date"];
            period_to: components["schemas"]["Date"];
            total_amount: components["schemas"]["Money"] | null;
            total_amount_words: string;
            copies_received: number | null;
            executor_signed: boolean | null;
            received_on: components["schemas"]["Date"];
            /** @enum {string} */
            received_channel: "" | "post" | "email" | "executor_portal" | "in_person" | "other";
            executor_sent_on: components["schemas"]["Date"];
            status: components["schemas"]["Status"];
            /** @enum {string} */
            decision: "" | "sign" | "refuse";
            rules_version: string;
            is_demo: boolean;
            demo_shift_days: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Timing: {
            /** @enum {string} */
            stage: "not_received" | "response_window" | "response_overdue" | "silent_accepted";
            day_number: number;
            days_left_response: number;
            days_left_silent: number;
        };
        Deadlines: {
            /** Format: date */
            response_on: string;
            /** Format: date */
            silent_on: string;
            timing: components["schemas"]["Timing"];
            basis: components["schemas"]["Basis"][];
        };
        Sums: {
            lines_total: components["schemas"]["Money"];
            disputed: components["schemas"]["Money"];
            disputed_count: number;
            unchecked_count: number;
            act_total: components["schemas"]["Money"] | null;
            /** @description Сумма строк не совпадает с итогом п. 2 акта */
            mismatch: boolean;
        };
        Line: {
            /** Format: uuid */
            id: string;
            position: number;
            work_name: string;
            pp290_ref: string;
            periodicity_qty: string;
            unit: string;
            unit_price: components["schemas"]["Money"] | null;
            amount: components["schemas"]["Money"];
            review_status: components["schemas"]["ReviewStatus"];
            comment: string;
            disputed_amount: components["schemas"]["Money"] | null;
            resident_visible: boolean;
            entrances: number[] | null;
            /** @description Строка оспаривалась в предыдущем акте */
            prev_disputed: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        LineInput: {
            work_name?: string;
            pp290_ref?: string;
            periodicity_qty?: string;
            unit?: string;
            /** @description Пустая строка — очистить */
            unit_price?: string | null;
            amount?: string;
            review_status?: components["schemas"]["ReviewStatus"];
            comment?: string;
            disputed_amount?: string | null;
            resident_visible?: boolean;
            entrances?: number[];
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            line_id: string | null;
            file_id: string | null;
            seq: number;
            /** @example Д-1 */
            code: string;
            note: string;
            author_role: string;
            mime: string;
            /** Format: date-time */
            created_at: string;
            /** @description Подписанная ссылка на файл */
            url?: string;
        };
        VoteSummary: {
            yes: number;
            no: number;
            unknown: number;
            comments: string[];
        };
        LineView: components["schemas"]["Line"] & {
            evidence: components["schemas"]["Evidence"][];
            residents: components["schemas"]["VoteSummary"] | null;
        };
        Document: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "cover_letter" | "refusal";
            file_id: string;
            version: number;
            rules_version: string;
            /** Format: date-time */
            created_at: string;
            url: string;
        };
        Dispatch: {
            id: string;
            document_id: string | null;
            channel: components["schemas"]["Channel"];
            channel_note: string;
            /** Format: date */
            sent_on: string;
            /** Format: date-time */
            created_at: string;
        };
        Event: {
            id: string;
            type: string;
            payload: Record<string, never>;
            /** Format: date-time */
            created_at: string;
        };
        ActView: {
            act: components["schemas"]["Act"];
            status_title: string;
            house: components["schemas"]["House"];
            /**
             * Format: date
             * @description «Сегодня» для акта (у демо-актов со сдвигом)
             */
            today: string;
            editable: boolean;
            deadlines: components["schemas"]["Deadlines"] | null;
            /** @description Проверки сроков исполнителя */
            checks: components["schemas"]["Claim"][];
            sums: components["schemas"]["Sums"];
            lines: components["schemas"]["LineView"][];
            documents: components["schemas"]["Document"][];
            dispatches: components["schemas"]["Dispatch"][] | null;
            events: components["schemas"]["Event"][];
            invite: {
                token: string;
                link: string;
            } | null;
            respondents: number;
            source_file_url: string | null;
            notes: components["schemas"]["Claim"][];
        };
        ActSummary: components["schemas"]["Act"] & {
            status_title: string;
            deadlines: components["schemas"]["Deadlines"] | null;
        };
        /** @description Любое подмножество полей; отсутствующие не меняются */
        HeaderPatch: {
            number?: string;
            act_date?: components["schemas"]["Date"];
            city?: string;
            address?: string;
            customer_full_name?: string;
            customer_apartment?: string;
            customer_authority_text?: string;
            executor_name?: string;
            executor_signatory_name?: string;
            executor_signatory_position?: string;
            executor_basis?: string;
            /** @enum {string} */
            contract_type?: "management" | "services" | "repair";
            contract_number?: string;
            contract_date?: components["schemas"]["Date"];
            contract_end_date?: components["schemas"]["Date"];
            period_from?: components["schemas"]["Date"];
            period_to?: components["schemas"]["Date"];
            total_amount?: string;
            total_amount_words?: string;
            copies_received?: number;
            executor_signed?: boolean;
            /** Format: date */
            received_on?: string;
            /** @enum {string} */
            received_channel?: "" | "post" | "email" | "executor_portal" | "in_person" | "other";
            executor_sent_on?: components["schemas"]["Date"];
        };
        ResidentLine: {
            id: string;
            position: number;
            work_name: string;
            periodicity_qty: string;
            entrances: number[] | null;
        };
        Vote: {
            /** Format: uuid */
            line_id: string;
            entrance_no?: number;
            /** @enum {string} */
            answer: "yes" | "no" | "unknown";
            comment?: string;
        };
        ResidentView: {
            act_number: string;
            address: string;
            period_from: components["schemas"]["Date"];
            period_to: components["schemas"]["Date"];
            entrances_count: number;
            open: boolean;
            is_demo: boolean;
            consented: boolean;
            lines: components["schemas"]["ResidentLine"][];
            my_votes: components["schemas"]["Vote"][];
        };
        VotesInput: {
            consent?: boolean;
            entrance_no: number;
            votes: components["schemas"]["Vote"][];
        };
        DecisionResult: {
            document: components["schemas"]["Document"];
            url: string;
            /** @description Файл отправлен ботом в чат председателя */
            delivered: boolean;
            warning?: string;
        };
        CatalogItem: {
            /** @example п. 23, абз. 4 */
            ref: string;
            section: string;
            text: string;
        };
    };
    responses: {
        /** @description Ошибка */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        Token: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    saveProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileBundle"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listActs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        acts: components["schemas"]["ActSummary"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createDemoAct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    patchAct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeaderPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    addLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineInput"];
            };
        };
        responses: {
            /** @description Создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    patchLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    addEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Передавать до поля file */
                    note?: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Сохранено */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
            415: components["responses"]["Error"];
        };
    };
    deleteEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        /** @example https://max.ru/t84_hakaton_max_bot?startapp=inv_7Qv7LXmjUv1atidE */
                        link: string;
                        /** @description Готовый текст для пересылки в чат дома */
                        text: string;
                        /** Format: date-time */
                        expires_at: string;
                    };
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentView"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            410: components["responses"]["Error"];
        };
    };
    putVotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VotesInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentView"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            410: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "sign" | "refuse";
                    /** @description Подтверждение подписания при спорных строках */
                    confirm_disputed?: boolean;
                };
            };
        };
        responses: {
            /** @description Сформирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    dispatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    channel: components["schemas"]["Channel"];
                    channel_note?: string;
                    /**
                     * Format: date
                     * @description По умолчанию — сегодня
                     */
                    sent_on?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    successor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    demoShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    days?: number;
                    /** @description Перейти к N-му дню после получения */
                    to_day?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActView"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    searchWorks: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CatalogItem"][];
                        source?: components["schemas"]["Source"];
                        edition: string;
                        note: string;
                    };
                };
            };
            422: components["responses"]["Error"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        rules: components["schemas"]["Basis"][];
                        params: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    getFile: {
        parameters: {
            query: {
                exp: string;
                sig: string;
                download?: "1";
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
